---
# Instalacja serwera repozytorium pakietów BA
# Wywołuje rolę z katalogu roles/ba_srv/tasks
# marcin_stec@pl.ibm.com

- hosts: ba_srvs
  gather_facts: True
  remote_user: root

  roles:
    - role: ba_srv
      repo_refresh: False # Ten playbook ma instalować świeży serwer.
      tags:
        - "BA_SRV"